#!/usr/bin/env python3
"""Materialize independent public YFM projects from the modular docs tree."""

from __future__ import annotations

import argparse
import json
import re
import shutil
import sys
from pathlib import Path
from typing import Any
from urllib.parse import urlsplit


MODULE_RE = re.compile(r"^[a-z0-9][a-z0-9-]*$")
PROJECT_NAME_RE = re.compile(r"^\s*project-name:\s*['\"]?([^'\"\s#]+)", re.MULTILINE)
CONFIG_LANGS_RE = re.compile(r"^[ \t]*langs:[ \t]*\[([^]]+)]", re.MULTILINE)
PRESET_SCALAR_RE = re.compile(r"^  ([A-Za-z0-9][A-Za-z0-9_.-]*):(?:\s+(.*?))?\s*$")
PLACEHOLDER_RE = re.compile(r"{{\s*([A-Za-z0-9][A-Za-z0-9_.-]*)\s*}}")
REVISION_QUERY_RE = re.compile(r"^$|^\?revision=[A-Za-z0-9._-]+$")
VIEWER_URL_RE = re.compile(
    r"^https://[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.viewer\.ydocs\.io$"
)
ROUTE_ROOT_RE = re.compile(r"{{\s*(landing|core|spyt|chyt|yql)-docs-root\s*}}")
MODULAR_ROUTE_RE = re.compile(
    r"{{\s*(?P<module>landing|core|spyt|chyt|yql)-docs-root\s*}}/"
    r"{{\s*lang\s*}}/"
    r"(?P<path>[A-Za-z0-9_./-]*)"
    r"{{\s*docs-revision-query\s*}}"
    r"(?:#[^\s)\]\[\"'<>]*)?"
)
DOCS_ROOT_PREFIX_RE = re.compile(r"{{\s*docs_root\s*}}/(?P<prefix>[^/\s)\]\[\"'<>]+)")
LEGACY_SELF_ROUTE_RE = re.compile(
    r"{{\s*docs_root\s*}}/"
    r"(?P<module>[a-z0-9][a-z0-9-]*)/"
    r"(?P<target>[^\s)\]\[\"'<>]+)"
)
LEGACY_ROUTE_PATH_RE = re.compile(r"^[A-Za-z0-9_./-]+$")
HARDCODED_SELF_ROUTE_RE = re.compile(
    r"https://ytsaurus\.tech/docs/"
    r"(?P<module>[a-z0-9][a-z0-9-]*)/"
    r"(?P<target>[^\s)\]\[\"'<>]+)"
)
OG_URL_PROPERTY_RE = re.compile(
    r"[ \t]*-[ \t]+property:[ \t]*['\"]og:url['\"][ \t]*"
)
HARDCODED_COMPONENT_RE = re.compile(
    r"https://ytsaurus\.tech/docs/(?P<module>core|spyt|chyt|yql)(?:/|\b)"
)
INDEX_NAMES = ("index.md", "index.yaml", "index.yml")
TEXT_SUFFIXES = {".md", ".yaml", ".yml"}
OUTPUT_MARKER = ".modular-docs-assembly-v1"
OUTPUT_MARKER_CONTENT = "Generated by assemble-modular-docs.py; safe to replace.\n"


class AssemblyError(RuntimeError):
    pass


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Create fresh YFM input roots from yt/docs/public and yt/docs/common."
    )
    parser.add_argument(
        "--registry",
        type=Path,
        default=Path(".github/docs-modules.json"),
        help="Module registry JSON.",
    )
    parser.add_argument(
        "--source-root",
        type=Path,
        default=Path("yt/docs"),
        help="Directory containing public/ and common/.",
    )
    parser.add_argument(
        "--output-root",
        type=Path,
        default=Path("_docs-input"),
        help="Generated input root.",
    )
    parser.add_argument(
        "--module",
        action="append",
        dest="modules",
        help="Assemble only this module. May be repeated.",
    )
    parser.add_argument(
        "--clean",
        action="store_true",
        help="Remove an existing output root before assembly.",
    )
    parser.add_argument(
        "--docs-revision-query",
        help=(
            "Override docs-revision-query while rendering Page Constructor YAML. "
            "Defaults to the value in public/presets.yaml."
        ),
    )
    preview_group = parser.add_mutually_exclusive_group()
    preview_group.add_argument(
        "--public-revision-preview",
        action="store_true",
        help=(
            "Inject testing-only docs-viewer settings into generated .yfm files: "
            "unrestrict-revision-access=true and no-index=true."
        ),
    )
    preview_group.add_argument(
        "--public-version-preview",
        action="store_true",
        help=(
            "Inject the same public testing settings and Viewer roots as a "
            "revision preview, but require an empty docs-revision-query."
        ),
    )
    return parser.parse_args()


def load_registry(path: Path) -> list[dict[str, Any]]:
    if not path.is_file():
        raise AssemblyError(f"Module registry is missing: {path}")
    try:
        document = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as error:
        raise AssemblyError(f"Cannot read module registry {path}: {error}") from error

    if document.get("schema_version") != 1:
        raise AssemblyError("Unsupported module registry schema_version")
    modules = document.get("modules")
    if not isinstance(modules, list) or not modules:
        raise AssemblyError("Module registry must contain a non-empty modules list")

    names: set[str] = set()
    project_names: set[str] = set()
    viewer_urls: set[str] = set()
    prefixes: set[str] = set()
    for index, module in enumerate(modules):
        if not isinstance(module, dict):
            raise AssemblyError(f"Module #{index + 1} must be an object")
        name = module.get("name")
        project_name = module.get("project_name")
        viewer_url = module.get("viewer_url")
        languages = module.get("languages")
        common = module.get("common")
        storage_prefix = module.get("storage_prefix")
        if not isinstance(name, str) or not MODULE_RE.fullmatch(name):
            raise AssemblyError(f"Invalid module name: {name!r}")
        if name in names:
            raise AssemblyError(f"Duplicate module name: {name}")
        if not isinstance(project_name, str) or not MODULE_RE.fullmatch(project_name):
            raise AssemblyError(f"Module {name} has invalid project_name")
        if project_name in project_names:
            raise AssemblyError(f"Duplicate project_name: {project_name}")
        if not isinstance(viewer_url, str) or not VIEWER_URL_RE.fullmatch(viewer_url):
            raise AssemblyError(
                f"Module {name} has invalid viewer_url; expected an HTTPS "
                "*.viewer.ydocs.io root without a path, query, fragment, or "
                "trailing slash"
            )
        if viewer_url in viewer_urls:
            raise AssemblyError(f"Duplicate viewer_url: {viewer_url}")
        if (
            not isinstance(languages, list)
            or not languages
            or any(not isinstance(language, str) or not MODULE_RE.fullmatch(language) for language in languages)
            or len(languages) != len(set(languages))
        ):
            raise AssemblyError(f"Module {name} has invalid languages")
        if not isinstance(common, bool):
            raise AssemblyError(f"Module {name} must declare common as a boolean")
        if not isinstance(storage_prefix, str) or not MODULE_RE.fullmatch(
            storage_prefix
        ):
            raise AssemblyError(f"Module {name} has invalid storage_prefix")
        if storage_prefix in prefixes:
            raise AssemblyError(f"Duplicate storage_prefix: {storage_prefix}")
        names.add(name)
        project_names.add(project_name)
        viewer_urls.add(viewer_url)
        prefixes.add(storage_prefix)
    return modules


def ensure_safe_output(source_root: Path, output_root: Path) -> None:
    source = source_root.resolve()
    output = output_root.resolve()
    if output == source or output in source.parents or source in output.parents:
        raise AssemblyError(
            f"Output root must not contain or be contained by source root: {output}"
        )
    if output == Path(output.anchor) or len(output.parts) < 3:
        raise AssemblyError(f"Refusing unsafe output root: {output}")


def reject_symlinks(root: Path) -> None:
    if root.is_symlink():
        raise AssemblyError(f"Symlinks are not allowed in documentation inputs: {root}")
    for path in root.rglob("*"):
        if path.is_symlink():
            raise AssemblyError(f"Symlinks are not allowed in documentation inputs: {path}")
        if path.name == "internal":
            raise AssemblyError(f"Internal documentation paths are not allowed: {path}")


def require_file(path: Path, description: str) -> None:
    if not path.is_file():
        raise AssemblyError(f"Missing {description}: {path}")


def parse_scalar(value: str) -> str:
    value = value.strip()
    if value.startswith('"'):
        try:
            parsed = json.loads(value)
        except json.JSONDecodeError as error:
            raise AssemblyError(f"Invalid quoted preset scalar {value!r}: {error}") from error
        if not isinstance(parsed, str):
            raise AssemblyError(f"Expected string preset scalar, found: {value!r}")
        return parsed
    if value.startswith("'") and value.endswith("'"):
        return value[1:-1].replace("''", "'")
    return value


def load_public_scalars(path: Path) -> dict[str, str]:
    """Read simple scalars directly under the public preset without a YAML dependency."""
    variables: dict[str, str] = {}
    in_public = False
    for line in path.read_text(encoding="utf-8").splitlines():
        if not in_public:
            if line == "public:":
                in_public = True
            continue
        if line and not line[0].isspace():
            break
        match = PRESET_SCALAR_RE.fullmatch(line)
        if not match or match.group(2) is None:
            continue
        variables[match.group(1)] = parse_scalar(match.group(2))
    if not in_public:
        raise AssemblyError(f"Preset has no public section: {path}")
    return variables


def preview_docs_roots(
    modules: list[dict[str, Any]], variables: dict[str, str]
) -> dict[str, str]:
    """Read testing viewer roots from the module registry."""
    overrides: dict[str, str] = {}
    for module in modules:
        variable = f"{module['name']}-docs-root"
        if variable not in variables:
            raise AssemblyError(
                f"Public revision preview is missing registered {variable} variable"
            )
        overrides[variable] = module["viewer_url"]
    return overrides


def override_public_scalars(path: Path, overrides: dict[str, str]) -> None:
    """Replace existing public preset scalars in a generated preset copy."""
    lines = path.read_text(encoding="utf-8").splitlines(keepends=True)
    in_public = False
    replaced: set[str] = set()
    for index, line in enumerate(lines):
        body = line.rstrip("\r\n")
        newline = line[len(body) :]
        if not in_public:
            if body == "public:":
                in_public = True
            continue
        if body and not body[0].isspace():
            break
        match = PRESET_SCALAR_RE.fullmatch(body)
        if not match:
            continue
        name = match.group(1)
        if name not in overrides:
            continue
        lines[index] = f"  {name}: {json.dumps(overrides[name])}{newline}"
        replaced.add(name)

    missing = sorted(set(overrides) - replaced)
    if missing:
        raise AssemblyError(
            f"Cannot override missing public preset scalars in {path}: "
            f"{', '.join(missing)}"
        )
    path.write_text("".join(lines), encoding="utf-8")


def render_template_file(
    path: Path, variables: dict[str, str], module: str, language: str
) -> None:
    text = path.read_text(encoding="utf-8")
    names = set(PLACEHOLDER_RE.findall(text))
    missing = sorted(name for name in names if name not in variables)
    if missing:
        raise AssemblyError(
            f"Unknown assembly-time variables in {module}/{language}: "
            f"{', '.join(missing)}"
        )
    rendered = PLACEHOLDER_RE.sub(lambda match: variables[match.group(1)], text)
    if PLACEHOLDER_RE.search(rendered):
        raise AssemblyError(
            f"Unresolved assembly-time variables in {module}/{language}: {path}"
        )
    path.write_text(rendered, encoding="utf-8")


def validate_language(module: str, language: str, root: Path) -> None:
    if not root.is_dir():
        raise AssemblyError(f"Module {module} is missing language directory: {root}")
    require_file(root / "toc.yaml", f"{module}/{language} toc.yaml")
    require_file(root / "presets.yaml", f"{module}/{language} presets.yaml")
    indexes = [root / name for name in INDEX_NAMES if (root / name).is_file()]
    if len(indexes) != 1:
        found = ", ".join(path.name for path in indexes) or "none"
        raise AssemblyError(
            f"Module {module}/{language} must contain exactly one index.*, found: {found}"
        )


def validate_project_name(config: Path, expected: str) -> None:
    content = config.read_text(encoding="utf-8")
    match = PROJECT_NAME_RE.search(content)
    if not match:
        raise AssemblyError(f"Cannot find docs-viewer project-name in {config}")
    actual = match.group(1)
    if actual != expected:
        raise AssemblyError(
            f"project-name mismatch in {config}: expected {expected}, found {actual}"
        )


def validate_config_languages(config: Path, expected: list[str]) -> None:
    matches = CONFIG_LANGS_RE.findall(config.read_text(encoding="utf-8"))
    if not matches:
        raise AssemblyError(f"Cannot find langs in {config}")
    parsed = [
        [item.strip().strip("'\"") for item in match.split(",")]
        for match in matches
    ]
    if any(languages != expected for languages in parsed):
        raise AssemblyError(
            f"langs mismatch in {config}: expected {expected}, found {parsed}"
        )


def validate_docs_roots(variables: dict[str, str]) -> None:
    for name in (
        "landing-docs-root",
        "core-docs-root",
        "spyt-docs-root",
        "chyt-docs-root",
        "yql-docs-root",
    ):
        value = variables.get(name)
        if not value:
            raise AssemblyError(f"Shared public preset is missing {name}")
        parsed = urlsplit(value)
        if (
            parsed.scheme != "https"
            or not parsed.netloc
            or parsed.query
            or parsed.fragment
            or value.endswith("/")
        ):
            raise AssemblyError(
                f"Shared public preset {name} must be an HTTPS root without "
                f"query, fragment, or trailing slash: {value!r}"
            )


def inject_public_revision_preview(config: Path) -> None:
    """Enable a public revision URL without allowing search-engine indexing."""
    content = config.read_text(encoding="utf-8")
    testing_keys = ("unrestrict-revision-access", "no-index")
    for key in testing_keys:
        if re.search(rf"^[ \t]*{re.escape(key)}[ \t]*:", content, re.MULTILINE):
            raise AssemblyError(
                f"Testing-only docs-viewer setting {key} must not be committed to {config}"
            )

    lines = content.splitlines(keepends=True)
    section_index = next(
        (
            index
            for index, line in enumerate(lines)
            if re.fullmatch(r"docs-viewer:[ \t]*(?:#.*)?\n?", line)
        ),
        None,
    )
    if section_index is None:
        raise AssemblyError(f"Cannot find docs-viewer section in {config}")

    section_end = len(lines)
    for index in range(section_index + 1, len(lines)):
        line = lines[index]
        if line.strip() and not line[0].isspace() and not line.lstrip().startswith("#"):
            section_end = index
            break

    injected = [
        "  # Testing-only settings injected by assemble-modular-docs.py.\n",
        "  unrestrict-revision-access: true\n",
        "  no-index: true\n",
    ]
    lines[section_index + 1 : section_index + 1] = injected
    config.write_text("".join(lines), encoding="utf-8")


def validate_route_path(target_module: str, target_path: str) -> None:
    normalized_path = target_path[:-1] if target_path.endswith("/") else target_path
    segments = normalized_path.split("/")
    if any(segment in {"", ".", ".."} for segment in segments):
        raise AssemblyError(
            f"Modular route contains an unsafe path: {target_module}/{target_path}"
        )


def validate_route_target(
    source_root: Path, target_module: str, target_path: str, languages: list[str]
) -> None:
    normalized_path = target_path[:-1] if target_path.endswith("/") else target_path
    if target_path:
        validate_route_path(target_module, target_path)
    if Path(normalized_path).suffix in {".md", ".yaml", ".yml"}:
        raise AssemblyError(
            f"Modular route must omit a source extension: {target_module}/{target_path}"
        )
    for language in languages:
        language_root = source_root / "public" / target_module / language
        candidates = (
            [language_root / name for name in INDEX_NAMES]
            if not normalized_path
            else [
                language_root / f"{normalized_path}{suffix}"
                for suffix in (".md", ".yaml", ".yml")
            ]
            + [language_root / normalized_path / name for name in INDEX_NAMES]
        )
        if not any(candidate.is_file() for candidate in candidates):
            raise AssemblyError(
                f"Modular route target is missing: {target_module}/{language}/{target_path}"
            )


def rewrite_self_routes(
    destination: Path, public_source: Path, module: str, languages: list[str]
) -> tuple[int, int]:
    """Rewrite validated monolith-style self links in an assembled module."""
    legacy_rewritten = 0
    hardcoded_rewritten = 0
    for language in languages:
        language_root = destination / language
        for file_path in language_root.rglob("*"):
            if not file_path.is_file() or file_path.suffix not in TEXT_SUFFIXES:
                continue
            text = file_path.read_text(encoding="utf-8")

            def is_canonical_og_url(content: str, match: re.Match[str]) -> bool:
                line_start = content.rfind("\n", 0, match.start()) + 1
                previous_lines = content[:line_start].splitlines()
                return bool(
                    previous_lines
                    and OG_URL_PROPERTY_RE.fullmatch(previous_lines[-1])
                )

            def render_target(target: str) -> str:
                if "?" in target:
                    raise AssemblyError(
                        f"Legacy self route already contains a query in {file_path}: {target}"
                    )
                if target.count("#") > 1:
                    raise AssemblyError(
                        f"Legacy self route has multiple fragments in {file_path}: {target}"
                    )
                route_path, separator, fragment = target.partition("#")
                if separator and not fragment:
                    raise AssemblyError(
                        f"Legacy self route has an empty fragment in {file_path}: {target}"
                    )
                if separator and any(character in fragment for character in "\\{}"):
                    raise AssemblyError(
                        f"Legacy self route has an unsafe fragment in {file_path}: {target}"
                    )
                if not LEGACY_ROUTE_PATH_RE.fullmatch(route_path):
                    raise AssemblyError(
                        f"Legacy self route has an unsafe path in {file_path}: {target}"
                    )
                source_had_md = route_path.endswith(".md")
                if source_had_md:
                    route_path = route_path[:-3]
                elif route_path.endswith((".yaml", ".yml")):
                    raise AssemblyError(
                        f"Legacy self route may only use an optional .md extension in "
                        f"{file_path}: {target}"
                    )
                validate_route_path(module, route_path)

                suffixes = (".md",) if source_had_md else (".md", ".yaml", ".yml")
                public_language_root = public_source / language
                candidates = [
                    public_language_root / f"{route_path}{suffix}"
                    for suffix in suffixes
                ]
                resolved = [candidate for candidate in candidates if candidate.is_file()]
                if len(resolved) != 1:
                    found = ", ".join(str(candidate) for candidate in resolved) or "none"
                    raise AssemblyError(
                        f"Legacy self route target must resolve exactly once in "
                        f"{module}/{language}: {route_path}; found {found}"
                    )

                suffix = f"#{fragment}" if separator else ""
                return (
                    f"{{{{ {module}-docs-root }}}}/{{{{ lang }}}}/{route_path}"
                    f"{{{{ docs-revision-query }}}}{suffix}"
                )

            def replace_legacy(match: re.Match[str]) -> str:
                nonlocal legacy_rewritten
                if match.group("module") != module:
                    return match.group(0)
                legacy_rewritten += 1
                return render_target(match.group("target"))

            def replace_hardcoded(match: re.Match[str]) -> str:
                nonlocal hardcoded_rewritten
                if match.group("module") != module:
                    return match.group(0)
                target = match.group("target")
                first_segment = target.split("/", 1)[0]
                if is_canonical_og_url(text, match):
                    if first_segment != language:
                        raise AssemblyError(
                            f"Canonical og:url language mismatch in {file_path}: {target}"
                        )
                    return match.group(0)
                if first_segment in languages:
                    if first_segment != language or "/" not in target:
                        raise AssemblyError(
                            f"Hardcoded self route language mismatch in {file_path}: {target}"
                        )
                    target = target.split("/", 1)[1]
                hardcoded_rewritten += 1
                return render_target(target)

            rendered = LEGACY_SELF_ROUTE_RE.sub(replace_legacy, text)
            rendered = HARDCODED_SELF_ROUTE_RE.sub(replace_hardcoded, rendered)
            remaining = [
                match.group(0)
                for match in DOCS_ROOT_PREFIX_RE.finditer(rendered)
                if match.group("prefix") == module
            ]
            if remaining:
                raise AssemblyError(
                    f"Legacy self route remains after rewrite in {file_path}: {remaining[0]}"
                )
            hardcoded_remaining = [
                match.group(0)
                for match in HARDCODED_SELF_ROUTE_RE.finditer(rendered)
                if match.group("module") == module
                and not is_canonical_og_url(rendered, match)
            ]
            if hardcoded_remaining:
                raise AssemblyError(
                    f"Hardcoded self route remains after rewrite in {file_path}: "
                    f"{hardcoded_remaining[0]}"
                )
            if rendered != text:
                file_path.write_text(rendered, encoding="utf-8")
    return legacy_rewritten, hardcoded_rewritten


def validate_modular_routes(source_root: Path, modules: list[dict[str, Any]]) -> None:
    registry = {module["name"]: module for module in modules}
    for source_module, module in registry.items():
        roots = [source_root / "public" / source_module]
        common_root = source_root / "common" / source_module
        if common_root.exists():
            roots.append(common_root)
        for root in roots:
            for path in root.rglob("*"):
                if not path.is_file() or path.suffix not in TEXT_SUFFIXES:
                    continue
                text = path.read_text(encoding="utf-8")
                relative_parts = path.relative_to(root).parts
                source_language = (
                    relative_parts[0]
                    if relative_parts and relative_parts[0] in module["languages"]
                    else None
                )
                route_roots = list(ROUTE_ROOT_RE.finditer(text))
                routes = list(MODULAR_ROUTE_RE.finditer(text))
                if len(route_roots) != len(routes):
                    raise AssemblyError(
                        f"Malformed modular route in {path}; expected "
                        "<module>-docs-root/lang/path/docs-revision-query with the "
                        "query before any fragment"
                    )
                for route in routes:
                    target_module = route.group("module")
                    target_path = route.group("path")
                    if target_path:
                        validate_route_path(target_module, target_path)
                    target = registry.get(target_module)
                    if target is None:
                        raise AssemblyError(
                            f"Modular route references unregistered module {target_module}: {path}"
                        )
                    target_languages = target["languages"]
                    if source_language is not None:
                        if source_language not in target_languages:
                            raise AssemblyError(
                                f"Modular route has no matching {source_language} target "
                                f"language in {path}"
                            )
                        target_languages = [source_language]
                    validate_route_target(
                        source_root,
                        target_module,
                        target_path,
                        target_languages,
                    )

                for match in DOCS_ROOT_PREFIX_RE.finditer(text):
                    prefix = match.group("prefix")
                    if prefix in registry and prefix != source_module:
                        raise AssemblyError(f"Legacy cross-module docs_root link in {path}")

                for match in HARDCODED_COMPONENT_RE.finditer(text):
                    if match.group("module") != source_module:
                        raise AssemblyError(f"Hardcoded cross-module link in {path}")


def assemble_module(
    module: dict[str, Any],
    source_root: Path,
    output_root: Path,
    shared_presets: Path,
    shared_variables: dict[str, str],
    docs_revision_query: str,
    public_preview_mode: str | None,
    preview_roots: dict[str, str],
) -> dict[str, Any]:
    name = module["name"]
    public_source = source_root / "public" / name
    if not public_source.is_dir():
        raise AssemblyError(f"Public module source is missing: {public_source}")
    reject_symlinks(public_source)

    config = public_source / ".yfm"
    require_file(config, f"{name} .yfm")
    validate_project_name(config, module["project_name"])
    validate_config_languages(config, module["languages"])
    if (public_source / "presets.yaml").exists():
        raise AssemblyError(
            f"Module {name} must use shared public/presets.yaml, but has its own root presets.yaml"
        )

    for language in module["languages"]:
        validate_language(name, language, public_source / language)

    destination = output_root / name
    if destination.exists():
        raise AssemblyError(f"Output collision for module {name}: {destination}")
    shutil.copytree(public_source, destination, copy_function=shutil.copy2)
    shutil.copy2(shared_presets, destination / "presets.yaml")
    if public_preview_mode:
        inject_public_revision_preview(destination / ".yfm")
        override_public_scalars(destination / "presets.yaml", preview_roots)

    common_module = source_root / "common" / name
    if module["common"]:
        if not common_module.is_dir():
            raise AssemblyError(f"Expected common source is missing: {common_module}")
        reject_symlinks(common_module)
        for language in module["languages"]:
            common_language = common_module / language
            if not common_language.is_dir():
                raise AssemblyError(
                    f"Module {name} is missing common/{name}/{language}"
                )
            common_destination = destination / language / "common"
            if common_destination.exists():
                raise AssemblyError(
                    f"Public/common collision for {name}/{language}: {common_destination}"
                )
            shutil.copytree(
                common_language, common_destination, copy_function=shutil.copy2
            )

        shared_images = common_module / "_images"
        if shared_images.exists():
            if not shared_images.is_dir():
                raise AssemblyError(
                    f"Module {name} common _images must be a directory: {shared_images}"
                )
            for language in module["languages"]:
                images_destination = destination / language / "_images"
                if images_destination.exists():
                    raise AssemblyError(
                        f"Public/shared image collision for {name}/{language}: "
                        f"{images_destination}"
                    )
                shutil.copytree(
                    shared_images, images_destination, copy_function=shutil.copy2
                )
    elif common_module.exists():
        raise AssemblyError(
            f"Module {name} declares common=false but common source exists: {common_module}"
        )

    legacy_self_routes_rewritten, hardcoded_self_routes_rewritten = rewrite_self_routes(
        destination, public_source, name, module["languages"]
    )

    for language in module["languages"]:
        language_root = destination / language
        language_presets = language_root / "presets.yaml"
        language_variables = load_public_scalars(language_presets)
        if public_preview_mode:
            # A language preset may define its own component root so that the
            # source module can also be built directly.  During a public
            # preview that value must not shadow the Viewer root injected into
            # the shared preset, otherwise self-links leave the preview and
            # point at production.
            language_preview_roots = {
                name: value
                for name, value in preview_roots.items()
                if name in language_variables
            }
            if language_preview_roots:
                override_public_scalars(
                    language_presets, language_preview_roots
                )
                language_variables = load_public_scalars(language_presets)
        variables = dict(shared_variables)
        variables.update(language_variables)
        variables["docs-revision-query"] = docs_revision_query
        if variables.get("lang") != language:
            raise AssemblyError(
                f"Language preset mismatch in {language_presets}: "
                f"expected lang={language!r}, found {variables.get('lang')!r}"
            )
        render_template_file(language_presets, variables, name, language)

        indexes = [
            language_root / item
            for item in INDEX_NAMES
            if (language_root / item).is_file()
        ]
        index = indexes[0]
        if index.suffix in {".yaml", ".yml"}:
            render_template_file(index, variables, name, language)

    return {
        "name": name,
        "project_name": module["project_name"],
        "viewer_url": module["viewer_url"],
        "storage_prefix": module["storage_prefix"],
        "languages": module["languages"],
        "common": module["common"],
        "public_revision_preview": public_preview_mode == "revision",
        "public_version_preview": public_preview_mode == "version",
        "legacy_self_routes_rewritten": legacy_self_routes_rewritten,
        "hardcoded_self_routes_rewritten": hardcoded_self_routes_rewritten,
        "output": str(destination),
    }


def run(args: argparse.Namespace) -> list[dict[str, Any]]:
    source_root = args.source_root.resolve()
    output_root = args.output_root.resolve()
    ensure_safe_output(source_root, output_root)

    if not source_root.is_dir():
        raise AssemblyError(f"Source root is missing: {source_root}")
    if (source_root / "internal").exists():
        raise AssemblyError(
            f"Public GitHub source must not contain internal/: {source_root / 'internal'}"
        )
    public_root = source_root / "public"
    common_root = source_root / "common"
    if not public_root.is_dir() or not common_root.is_dir():
        raise AssemblyError("Source root must contain public/ and common/")
    reject_symlinks(public_root)
    reject_symlinks(common_root)

    shared_presets = public_root / "presets.yaml"
    require_file(shared_presets, "shared public presets.yaml")
    reject_symlinks(shared_presets)
    shared_variables = load_public_scalars(shared_presets)
    docs_revision_query = (
        args.docs_revision_query
        if args.docs_revision_query is not None
        else shared_variables.get("docs-revision-query", "")
    )
    if not REVISION_QUERY_RE.fullmatch(docs_revision_query):
        raise AssemblyError(
            "docs-revision-query must be empty or match ?revision=<safe-revision>"
        )

    modules = load_registry(args.registry.resolve())
    public_preview_mode: str | None = None
    if args.public_revision_preview:
        public_preview_mode = "revision"
        if not docs_revision_query:
            raise AssemblyError(
                "--public-revision-preview requires a non-empty --docs-revision-query"
            )
    elif args.public_version_preview:
        public_preview_mode = "version"
        if docs_revision_query:
            raise AssemblyError(
                "--public-version-preview requires an empty --docs-revision-query"
            )

    preview_roots: dict[str, str] = {}
    if public_preview_mode:
        preview_roots = preview_docs_roots(modules, shared_variables)
        shared_variables.update(preview_roots)
    validate_docs_roots(shared_variables)
    validate_modular_routes(source_root, modules)
    if args.modules:
        requested = set(args.modules)
        known = {module["name"] for module in modules}
        unknown = requested - known
        if unknown:
            raise AssemblyError(f"Unknown requested modules: {', '.join(sorted(unknown))}")
        modules = [module for module in modules if module["name"] in requested]

    if output_root.exists():
        if not args.clean:
            raise AssemblyError(
                f"Output root already exists; pass --clean to replace it: {output_root}"
            )
        marker = output_root / OUTPUT_MARKER
        if (
            not marker.is_file()
            or marker.read_text(encoding="utf-8") != OUTPUT_MARKER_CONTENT
        ):
            raise AssemblyError(
                f"Refusing to clean unmarked output root: {output_root}"
            )
        shutil.rmtree(output_root)
    output_root.mkdir(parents=True)
    (output_root / OUTPUT_MARKER).write_text(
        OUTPUT_MARKER_CONTENT, encoding="utf-8"
    )

    assembled = [
        assemble_module(
            module,
            source_root,
            output_root,
            shared_presets,
            shared_variables,
            docs_revision_query,
            public_preview_mode,
            preview_roots,
        )
        for module in modules
    ]
    manifest = {
        "schema_version": 1,
        "source_root": str(source_root),
        "modules": assembled,
    }
    (output_root / "assembly-manifest.json").write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    return assembled


def main() -> int:
    args = parse_args()
    try:
        assembled = run(args)
    except (AssemblyError, OSError, UnicodeError) as error:
        print(f"assemble-modular-docs: {error}", file=sys.stderr)
        return 1
    for module in assembled:
        languages = ",".join(module["languages"])
        print(
            f"assembled {module['name']} ({module['project_name']}; {languages}) "
            f"-> {module['output']}"
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
