name: Docs Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - ogorbacheva-test-algola
    paths: 'yt/docs/**'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        uses: diplodoc-platform/docs-build-action
        with:
          revision: "${{ github.sha }}"
          src-root: "./yt/docs"
          api-key: ${{ secrets.ALGOLIA_API_KEY }} # Это Write Key
          app-id: WW7EWG7Y6T
          index-name: "test_ytsaurus-doc"
      - name: Upload built docs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: built-docs  # Имя артефакта (можно изменить; если в docs указано иное — используйте то)
          path: ./_docs-build  # Дефолтный путь из документации


  algolia-index:
    needs: build
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download built docs artifact
        uses: actions/download-artifact@v4
        with:
          name: built-docs  # Должно совпадать с именем в upload
          path: ./_docs-build

      - name: List output docs
        run: |
          ls ./_docs-build/ru/

      - name: Upload index to Algolia
        env:
          ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }} # Это Write Key
          ALGOLIA_APP_ID: WW7EWG7Y6T
          ALGOLIA_INDEX_NAME: "test_ytsaurus-doc"
        run: |
         npm install -g @diplodoc/cli @diplodoc/algolia-extension
         yfm index -i ./_docs-build --extensions "$(npm root -g)/@diplodoc/algolia-extension"
         ls -la ./_docs-build/




